# Generated by Django 3.1 on 2020-08-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSP_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', models.CharField(choices=[('Onion', 'Onion'), ('Cheese', 'Cheese'), ('Mushroom', 'Mushroom'), ('Bellpepper', 'Bellpepper'), ('Sweetcorn', 'Sweetcorn'), ('Panner', 'Panner')], max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('food_type', models.ManyToManyField(to='Pizzas.Food_type')),
            ],
        ),
    ]
