# Generated by Django 3.1 on 2020-08-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSP_Pizza',
            new_name='Chef_Pizzas',
        ),
    ]
