# Generated by Django 3.1 on 2020-08-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0002_auto_20200828_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chef_pizzas',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='chef_pizzas',
            name='ingredient',
            field=models.ManyToManyField(to='Pizzas.Ingredients'),
        ),
    ]
