# Generated by Django 3.1 on 2020-08-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sspizza', '0004_auto_20200828_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('baseCrust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sspizza.crust')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sspizza.pizza')),
                ('topping', models.ManyToManyField(to='sspizza.Topping')),
            ],
        ),
    ]
