# Generated by Django 3.1 on 2020-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspizza', '0005_ordercart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='baseCrust',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='topping',
        ),
        migrations.AddField(
            model_name='ordercart',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
