# Generated by Django 3.1 on 2020-09-03 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sspizza', '0007_pizza_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
