# Generated by Django 3.1 on 2020-09-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sspizza', '0008_auto_20200903_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='created_by',
        ),
    ]
